### ISSUE TITLE
Enhancing AssignmentSession.plot_spectrum()

### ISSUE THREAD

**Issue by aowen-uwmad** [laserkelvin/PySpecTools#19]
Our group is used to looking at the spectrum using the intensity, and this is what is initially plotted when using `.plot_spectrum()`  of an `AssignmentSession` before doing any peak finding. Which makes it particularly jarring when using `.plot_spectrum()` after peak finding and it "appears" to have completely changed. 

There are two main improvements I'd like to make.

1. _Add y-axis label_. 
This will help make it clear what data is being plotted. 
`fig.layout["yaxis"]["title"] = desired_y_label_str`

2. _Add option for what type of data is being plotted_. 
In case we'd like to view the spectrum using intensity after peak finding.
Could just add a variable call in the function definition and have the user pass the column name of the dataframe they'd like to plot. I'd suggest also adding checks to make sure the `SNR` column exists before trying to plot that.

**Comment by laserkelvin** [comment]
The units change after peak finding to units of signal-to-noise: this is simply a conventional because raw intensity units do not necessarily mean anything to others (i.e. a raw volts scale is meaningless without specifying gain, etc). The choice to make it plot in units of SNR is simply a matter for consistency between groups, both in the generated report as well as for publications.

If you change the `int_col` attribute of an `AssignmentSession` object, all the plotting and whatnot will be done with that column, regardless of whether you've run `peak_find` or not. That answers your second point.

Would you like to build the _y-axis_ label change in, and submit a PR?

I have yet to write up a proper guide on how to do this, but if you can take a look at [`astropy`'s documentation](https://docs.astropy.org/en/stable/development/workflow/development_workflow.html) on good practice for setting up environments for new features/PR's. Please feel free to ask if you're unsure about anything.

**Comment by aowen-uwmad** [comment]
Changing the attribute is definitely a simpler way of getting the desired result. 
I will work on adding the _y-axis_ label, following the guide you suggested.

**Comment by laserkelvin** [comment]
Closing because PR #22 was merged.
